### ISSUE TITLE
On my win 7 , it's not working

### ISSUE THREAD

**Issue by JaosnHsieh** [derhuerst/casket#7]
I open my cmd.exe on windows 7 
then I done installation
 npm install -g casket -> done 

then I tried

casket [--name my-little-server] [--dir D:/]
or
casket [--name my-little-server] [--dir D:]
or
casket --name jason-server --dir D:/

it's stuck and not respond anything.

How can I start this server? 

Thanks in advance !

**Comment by derhuerst** [comment]
Hey!

The brackets in `casket [--name my-little-server] [--dir D:/]` are supposed to indicate that the `--name` and `--dir` parameters are optional. The last command you mentioned however is correct:

```
casket --name jason-server --dir D:/
```

Depending on your terminal you may have to wrap your arguments in quotation marks, e.g. `casket --name "jason-server" --dir "D:/"`.

> it's stuck and not respond anything.

Have you tried opening `http://localhost:8000` when it's running?

**Comment by derhuerst** [comment]
Will close this issue. Please reopen if the problem still persists.

**Comment by JaosnHsieh** [comment]
cheers ! 
after trying , it works on the terminal : Cygwin64 Terminal but not windows7 cmd.exe.
